//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrder.Entities
{
    using System;
    using System.Collections.Generic;
    public partial class Food
    {
        public Food()
        {
            this.Order = new HashSet<Order>();
            this.Score = new HashSet<Score>();
        }
    
        public int ID { get; set; }
        public string NameOfTheFood { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public Nullable<double> AverageScore { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Score> Score { get; set; }
    }
}
