//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrder.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Food = new HashSet<Food>();
            this.Person = new HashSet<Person>();
        }
    
        public int ID { get; set; }
        public string RestaurantName { get; set; }
        public string Address { get; set; }
        public int PhoneNumber { get; set; }
        public int DeliveryPrice { get; set; }
    
        public virtual ICollection<Food> Food { get; set; }
        public virtual ICollection<Person> Person { get; set; }
    }
}
