//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrder.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ID { get; set; }
        public int ReviewScore { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> FoodID { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Person Person { get; set; }
    }
}
